#!/usr/bin/env python

##
## Usage: runJob_merge MyJob
## (Note that if your jobs are not finished, it will wait patiently for them.)
##

import ROOT
import sys 
ROOT.EL.Driver.wait(sys.argv[1])

sys.exit()
